/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'blanthrip' at '8/14/16 2:07 PM' with Gradle 2.14
 *
 * @author blanthrip, @date 8/14/16 2:07 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
