/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'blanthrip' at '8/14/16 2:49 PM' with Gradle 2.14
 *
 * @author blanthrip, @date 8/14/16 2:49 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
