/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'blanthrip' at '8/14/16 6:33 PM' with Gradle 2.14
 *
 * @author blanthrip, @date 8/14/16 6:33 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
