/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'blanthrip' at '8/14/16 6:33 PM' with Gradle 2.14
 *
 * @author blanthrip, @date 8/14/16 6:33 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
